### ISSUE TITLE
wrong time checking in phone_backend

### ISSUE THREAD

**Issue by AriaMoradi** [wejhink/django-phone-login#22] opened 2019-07-08 11:51 UTC
hi.
there is a bug in this code from `phone_login.backends.phone_backend`
```
timestamp_difference = datetime.datetime.now() - datetime.timedelta(
            minutes=getattr(settings, 'PHONE_LOGIN_MINUTES', 10)
        )
```
`datetime.datetime.now()` generates local time of the machine that the code is running on which is wrong because `PhoneToken` timestamps are time zone aware:
`timestamp = models.DateTimeField(auto_now_add=True, editable=False)`

fix:
use `django.utils.timezone.now()` insted of `datetime.datetime.now()`

**Comment by iraycd** [comment] 2019-08-23 16:28
Duplicate of this issue. Hence closing this issue. #21

**Closed as completed by iraycd** 2019-08-23 16:28 UTC
